const phrases = [
  "Scanning the depths of knowledge for the perfect goals.",
  "Generating personalized goals just for you.",
  "Crafting a roadmap for your programming journey.",
  "Brainstorming the best ways to learn your chosen programming skill.",
  "Mining the vast expanse of programming knowledge for ideas.",
  "Preparing a tailor-made learning plan just for you.",
  "Sifting through the endless possibilities for your learning goals.",
  "Consulting with the experts to curate your perfect learning plan.",
  "Preparing a list of actionable goals to take your programming to the next level.",
  "Assembling a learning plan that's both comprehensive and achievable.",
  "Putting together a customized roadmap to programming success.",
  "Preparing a learning plan that's tailored to your unique needs.",
  "Curating a list of goals to help you master your chosen programming skill.",
  "Delving deep into the world of programming to find the best learning goals.",
  "Researching the most effective ways to learn your desired programming skill.",
  "Using my expertise to help you achieve your programming goals.",
  "Creating a personalized action plan to help you reach your programming objectives.",
  "Investigating the best strategies for learning your chosen programming skill.",
  "Building a learning plan that's both practical and effective.",
  "Assembling a list of goals to help you become a programming pro.",
  "Combining my knowledge with your passion to create a winning learning plan.",
  "Culling the most effective learning strategies to help you achieve your goals.",
  "Generating a customized plan to help you take your programming to the next level.",
  "Focusing on your unique strengths to create a plan that works for you.",
  "Aggregating the best programming resources to help you achieve your goals.",
  "Constructing a plan that's designed to help you succeed at programming.",
  "Compiling a list of achievable goals to help you master your programming skills.",
  "Assembling a learning plan that's tailored to your specific learning style.",
  "Using my expertise to create a learning plan that's tailored to your goals.",
  "Sifting through the myriad of programming resources to find the best learning materials.",
  "Gathering the most effective strategies for learning your chosen programming skill.",
  "Researching the most up-to-date programming resources to help you achieve your goals.",
  "Customizing a plan that's tailored to your unique needs and goals.",
  "Curating a list of goals that's both comprehensive and achievable.",
  "Investigating the most effective ways to learn your chosen programming skill.",
  "Creating a plan that's designed to help you achieve your programming objectives.",
  "Aggregating the most effective programming resources to help you reach your goals.",
  "Assembling a comprehensive list of goals to help you master your programming skills.",
  "Using my expertise to help you design a learning plan that works for you.",
  "Focusing on your specific learning goals to create a plan that's tailored to you.",
  "Compiling a list of the most effective programming resources for your learning journey.",
  "Generating a personalized plan to help you achieve your programming objectives.",
  "Sifting through the programming world to find the best resources for your goals.",
  "Crafting a learning plan that's both challenging and achievable.",
  "Building a plan that's tailored to your specific needs and learning style.",
  "Curating a list of goals that's both ambitious and realistic.",
  "Researching the most innovative strategies for learning your chosen programming skill.",
  "Investigating the most effective ways to help you achieve your programming goals.",
  "Assembling a list of resources to help you overcome programming roadblocks.",
  "Researching the most popular programming tools to help you achieve your goals.",
  "Gathering the most effective study techniques to help you learn your chosen programming skill.",
  "Digging deep into the programming world to find the best learning resources.",
  "Creating a personalized plan to help you reach your programming objectives.",
  "Investigating the most effective strategies for learning programming concepts.",
  "Aggregating the most effective resources to help you master your programming skills.",
  "Crafting a learning plan that's tailored to your individual needs and goals.",
  "Combining the most effective learning strategies to create a winning plan.",
  "Preparing a list of achievable goals to help you become a programming master.",
];


export default function getRandomPhrase() {
    const randomIndex = Math.floor(Math.random() * phrases.length);
    return phrases[randomIndex];
}